name: Sleep Jobs Workflow

on: workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job6:
    runs-on: ubuntu-latest
    needs: 
      - job5
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job7:
    runs-on: ubuntu-latest
    needs: job6
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job8:
    runs-on: ubuntu-latest
    needs: job6
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job9:
    runs-on: ubuntu-latest
    needs: job6
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  job10:
    runs-on: ubuntu-latest
    needs:
      - job9
      - job8
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Sleep for 10 seconds
        run: sleep 10
